
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ADMIN
 */
public class renew extends javax.swing.JFrame {

    /**
     * Creates new form VisitorLog
     */
    public renew() {
        initComponents();
    }
//    private javax.swing.JTextField searchField;        // For registration number search
//    private javax.swing.JButton searchButton;          // To trigger search
           // To display/edit name
//    private javax.swing.JTextField phoneField;         // To display/edit phone
//    private javax.swing.JTextField regNoField;         // To display reg no
//    private javax.swing.JTextField periodField;        // To display/edit period
//    private javax.swing.JTextArea addressField;        // To display/edit address
//    private javax.swing.JButton renewButton;           // To save renewed details
//    private javax.swing.JButton backButton;            // To go back to main
//    private javax.swing.JLabel searchLabel;            // "Enter Registration No:"
//    private javax.swing.JLabel nameLabel;              // "Name:"
//    private javax.swing.JLabel phoneLabel;             // "Phone No:"
//    private javax.swing.JLabel regNoLabel;             // "Registration No:"
//    private javax.swing.JLabel periodLabel;            // "Period:"
//    private javax.swing.JLabel addressLabel;           // "Address:"
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        addressField = new javax.swing.JTextField();
        periodField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        phoneField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        renewButton = new javax.swing.JToggleButton();
        jLabel9 = new javax.swing.JLabel();
        searchField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);
        jPanel1.add(addressField);
        addressField.setBounds(290, 190, 160, 60);

        periodField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                periodFieldActionPerformed(evt);
            }
        });
        jPanel1.add(periodField);
        periodField.setBounds(290, 160, 100, 22);

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel5.setText("ADDRESS");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(120, 200, 60, 18);

        jLabel6.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel6.setText("YEARLY/SEMI-ANNUAL");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(120, 160, 170, 18);

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 160, 0, 0);

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel2.setText("PHONE No.");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(120, 110, 80, 18);

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel1.setText("reg no");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 40, 60, 18);

        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });
        jPanel1.add(nameField);
        nameField.setBounds(290, 90, 100, 22);

        phoneField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneFieldActionPerformed(evt);
            }
        });
        jPanel1.add(phoneField);
        phoneField.setBounds(290, 120, 100, 22);

        jLabel7.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jLabel7.setText("Pass Renewal");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(210, 10, 250, 24);

        jToggleButton1.setBackground(new java.awt.Color(204, 204, 204));
        jToggleButton1.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jToggleButton1.setText("Back to home");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton1);
        jToggleButton1.setBounds(400, 10, 119, 27);

        renewButton.setBackground(new java.awt.Color(204, 204, 204));
        renewButton.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        renewButton.setText("Renew");
        renewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                renewButtonActionPerformed(evt);
            }
        });
        jPanel1.add(renewButton);
        renewButton.setBounds(300, 280, 90, 27);

        jLabel9.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel9.setText("NAME");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(120, 80, 39, 18);

        searchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFieldActionPerformed(evt);
            }
        });
        jPanel1.add(searchField);
        searchField.setBounds(90, 40, 90, 22);

        searchButton.setText("search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        jPanel1.add(searchButton);
        searchButton.setBounds(190, 40, 70, 25);

        jTabbedPane1.addTab("", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void periodFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_periodFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_periodFieldActionPerformed

    private void phoneFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneFieldActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
           Main mn = new Main();
        mn.setVisible(true);
        dispose();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void renewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_renewButtonActionPerformed
        // TODO add your handling code here:
       try (Connection con = DBconnection.connect()) {
        if (con == null) {
            JOptionPane.showMessageDialog(this, "Database connection failed!");
            return;
        }
        
        String query = "UPDATE register SET name=?, phoneNo=?, period=?, address=? WHERE registrationNo=?";
        try (PreparedStatement pst = con.prepareStatement(query)) {
            pst.setString(1, nameField.getText());
            pst.setString(2, phoneField.getText());
            pst.setString(3, periodField.getText());
            pst.setString(4, addressField.getText());
            pst.setString(5, searchField.getText());

            
            int result = pst.executeUpdate();
            if (result > 0) {
                JOptionPane.showMessageDialog(this, "Renewal completed successfully!");
                clearFields();
                enableFields(false);
            } else {
                JOptionPane.showMessageDialog(this, "Renewal failed!");
            }
        }
    } catch (SQLException ex) {
        Logger.getLogger(renew.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(this, "Error updating data: " + ex.getMessage());
    }
}

// Helper method to clear form fields
private void clearFields() {
    nameField.setText("");
    phoneField.setText("");
    periodField.setText("");
    addressField.setText("");
    }//GEN-LAST:event_renewButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
         String searchRegNo = searchField.getText();
    
    // Check if searchField is null or empty
    if (searchField == null || searchRegNo.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter a registration number.");
        return;
    }
    
    try (Connection con = DBconnection.connect()) {
        if (con == null) {
            JOptionPane.showMessageDialog(this, "Database connection failed!");
            return;
        }
        
        String query = "SELECT * FROM register WHERE registrationNo = ?";
        try (PreparedStatement pst = con.prepareStatement(query)) {
            pst.setString(1, searchRegNo);
            ResultSet rs = pst.executeQuery();
            
            if (rs.next()) {
                // Populate fields with data from database
                nameField.setText(rs.getString("name"));
                phoneField.setText(rs.getString("phoneNo"));
                periodField.setText(rs.getString("period"));
                addressField.setText(rs.getString("address"));
                
                enableFields(true);
            } else {
                JOptionPane.showMessageDialog(this, "No registration found with this number!");
                clearFields();
                enableFields(false);
            }
        }
    } catch (SQLException ex) {
        Logger.getLogger(renew.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(this, "Error fetching data: " + ex.getMessage());
    }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchFieldActionPerformed
private void enableFields(boolean enable) {
    nameField.setEditable(enable);
    phoneField.setEditable(enable);
    periodField.setEditable(enable);
    addressField.setEditable(enable);
    renewButton.setEnabled(enable);
}
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField periodField;
    private javax.swing.JTextField phoneField;
    private javax.swing.JToggleButton renewButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchField;
    // End of variables declaration//GEN-END:variables
}
